	computer_system u0 (
		.clk_clk                        (<connected-to-clk_clk>),                        //             clk.clk
		.pcie_hip_ctrl_test_in          (<connected-to-pcie_hip_ctrl_test_in>),          //   pcie_hip_ctrl.test_in
		.pcie_hip_ctrl_simu_mode_pipe   (<connected-to-pcie_hip_ctrl_simu_mode_pipe>),   //                .simu_mode_pipe
		.pcie_hip_pipe_sim_pipe_pclk_in (<connected-to-pcie_hip_pipe_sim_pipe_pclk_in>), //   pcie_hip_pipe.sim_pipe_pclk_in
		.pcie_hip_pipe_sim_pipe_rate    (<connected-to-pcie_hip_pipe_sim_pipe_rate>),    //                .sim_pipe_rate
		.pcie_hip_pipe_sim_ltssmstate   (<connected-to-pcie_hip_pipe_sim_ltssmstate>),   //                .sim_ltssmstate
		.pcie_hip_pipe_eidleinfersel0   (<connected-to-pcie_hip_pipe_eidleinfersel0>),   //                .eidleinfersel0
		.pcie_hip_pipe_eidleinfersel1   (<connected-to-pcie_hip_pipe_eidleinfersel1>),   //                .eidleinfersel1
		.pcie_hip_pipe_eidleinfersel2   (<connected-to-pcie_hip_pipe_eidleinfersel2>),   //                .eidleinfersel2
		.pcie_hip_pipe_eidleinfersel3   (<connected-to-pcie_hip_pipe_eidleinfersel3>),   //                .eidleinfersel3
		.pcie_hip_pipe_powerdown0       (<connected-to-pcie_hip_pipe_powerdown0>),       //                .powerdown0
		.pcie_hip_pipe_powerdown1       (<connected-to-pcie_hip_pipe_powerdown1>),       //                .powerdown1
		.pcie_hip_pipe_powerdown2       (<connected-to-pcie_hip_pipe_powerdown2>),       //                .powerdown2
		.pcie_hip_pipe_powerdown3       (<connected-to-pcie_hip_pipe_powerdown3>),       //                .powerdown3
		.pcie_hip_pipe_rxpolarity0      (<connected-to-pcie_hip_pipe_rxpolarity0>),      //                .rxpolarity0
		.pcie_hip_pipe_rxpolarity1      (<connected-to-pcie_hip_pipe_rxpolarity1>),      //                .rxpolarity1
		.pcie_hip_pipe_rxpolarity2      (<connected-to-pcie_hip_pipe_rxpolarity2>),      //                .rxpolarity2
		.pcie_hip_pipe_rxpolarity3      (<connected-to-pcie_hip_pipe_rxpolarity3>),      //                .rxpolarity3
		.pcie_hip_pipe_txcompl0         (<connected-to-pcie_hip_pipe_txcompl0>),         //                .txcompl0
		.pcie_hip_pipe_txcompl1         (<connected-to-pcie_hip_pipe_txcompl1>),         //                .txcompl1
		.pcie_hip_pipe_txcompl2         (<connected-to-pcie_hip_pipe_txcompl2>),         //                .txcompl2
		.pcie_hip_pipe_txcompl3         (<connected-to-pcie_hip_pipe_txcompl3>),         //                .txcompl3
		.pcie_hip_pipe_txdata0          (<connected-to-pcie_hip_pipe_txdata0>),          //                .txdata0
		.pcie_hip_pipe_txdata1          (<connected-to-pcie_hip_pipe_txdata1>),          //                .txdata1
		.pcie_hip_pipe_txdata2          (<connected-to-pcie_hip_pipe_txdata2>),          //                .txdata2
		.pcie_hip_pipe_txdata3          (<connected-to-pcie_hip_pipe_txdata3>),          //                .txdata3
		.pcie_hip_pipe_txdatak0         (<connected-to-pcie_hip_pipe_txdatak0>),         //                .txdatak0
		.pcie_hip_pipe_txdatak1         (<connected-to-pcie_hip_pipe_txdatak1>),         //                .txdatak1
		.pcie_hip_pipe_txdatak2         (<connected-to-pcie_hip_pipe_txdatak2>),         //                .txdatak2
		.pcie_hip_pipe_txdatak3         (<connected-to-pcie_hip_pipe_txdatak3>),         //                .txdatak3
		.pcie_hip_pipe_txdetectrx0      (<connected-to-pcie_hip_pipe_txdetectrx0>),      //                .txdetectrx0
		.pcie_hip_pipe_txdetectrx1      (<connected-to-pcie_hip_pipe_txdetectrx1>),      //                .txdetectrx1
		.pcie_hip_pipe_txdetectrx2      (<connected-to-pcie_hip_pipe_txdetectrx2>),      //                .txdetectrx2
		.pcie_hip_pipe_txdetectrx3      (<connected-to-pcie_hip_pipe_txdetectrx3>),      //                .txdetectrx3
		.pcie_hip_pipe_txelecidle0      (<connected-to-pcie_hip_pipe_txelecidle0>),      //                .txelecidle0
		.pcie_hip_pipe_txelecidle1      (<connected-to-pcie_hip_pipe_txelecidle1>),      //                .txelecidle1
		.pcie_hip_pipe_txelecidle2      (<connected-to-pcie_hip_pipe_txelecidle2>),      //                .txelecidle2
		.pcie_hip_pipe_txelecidle3      (<connected-to-pcie_hip_pipe_txelecidle3>),      //                .txelecidle3
		.pcie_hip_pipe_txdeemph0        (<connected-to-pcie_hip_pipe_txdeemph0>),        //                .txdeemph0
		.pcie_hip_pipe_txdeemph1        (<connected-to-pcie_hip_pipe_txdeemph1>),        //                .txdeemph1
		.pcie_hip_pipe_txdeemph2        (<connected-to-pcie_hip_pipe_txdeemph2>),        //                .txdeemph2
		.pcie_hip_pipe_txdeemph3        (<connected-to-pcie_hip_pipe_txdeemph3>),        //                .txdeemph3
		.pcie_hip_pipe_txmargin0        (<connected-to-pcie_hip_pipe_txmargin0>),        //                .txmargin0
		.pcie_hip_pipe_txmargin1        (<connected-to-pcie_hip_pipe_txmargin1>),        //                .txmargin1
		.pcie_hip_pipe_txmargin2        (<connected-to-pcie_hip_pipe_txmargin2>),        //                .txmargin2
		.pcie_hip_pipe_txmargin3        (<connected-to-pcie_hip_pipe_txmargin3>),        //                .txmargin3
		.pcie_hip_pipe_txswing0         (<connected-to-pcie_hip_pipe_txswing0>),         //                .txswing0
		.pcie_hip_pipe_txswing1         (<connected-to-pcie_hip_pipe_txswing1>),         //                .txswing1
		.pcie_hip_pipe_txswing2         (<connected-to-pcie_hip_pipe_txswing2>),         //                .txswing2
		.pcie_hip_pipe_txswing3         (<connected-to-pcie_hip_pipe_txswing3>),         //                .txswing3
		.pcie_hip_pipe_phystatus0       (<connected-to-pcie_hip_pipe_phystatus0>),       //                .phystatus0
		.pcie_hip_pipe_phystatus1       (<connected-to-pcie_hip_pipe_phystatus1>),       //                .phystatus1
		.pcie_hip_pipe_phystatus2       (<connected-to-pcie_hip_pipe_phystatus2>),       //                .phystatus2
		.pcie_hip_pipe_phystatus3       (<connected-to-pcie_hip_pipe_phystatus3>),       //                .phystatus3
		.pcie_hip_pipe_rxdata0          (<connected-to-pcie_hip_pipe_rxdata0>),          //                .rxdata0
		.pcie_hip_pipe_rxdata1          (<connected-to-pcie_hip_pipe_rxdata1>),          //                .rxdata1
		.pcie_hip_pipe_rxdata2          (<connected-to-pcie_hip_pipe_rxdata2>),          //                .rxdata2
		.pcie_hip_pipe_rxdata3          (<connected-to-pcie_hip_pipe_rxdata3>),          //                .rxdata3
		.pcie_hip_pipe_rxdatak0         (<connected-to-pcie_hip_pipe_rxdatak0>),         //                .rxdatak0
		.pcie_hip_pipe_rxdatak1         (<connected-to-pcie_hip_pipe_rxdatak1>),         //                .rxdatak1
		.pcie_hip_pipe_rxdatak2         (<connected-to-pcie_hip_pipe_rxdatak2>),         //                .rxdatak2
		.pcie_hip_pipe_rxdatak3         (<connected-to-pcie_hip_pipe_rxdatak3>),         //                .rxdatak3
		.pcie_hip_pipe_rxelecidle0      (<connected-to-pcie_hip_pipe_rxelecidle0>),      //                .rxelecidle0
		.pcie_hip_pipe_rxelecidle1      (<connected-to-pcie_hip_pipe_rxelecidle1>),      //                .rxelecidle1
		.pcie_hip_pipe_rxelecidle2      (<connected-to-pcie_hip_pipe_rxelecidle2>),      //                .rxelecidle2
		.pcie_hip_pipe_rxelecidle3      (<connected-to-pcie_hip_pipe_rxelecidle3>),      //                .rxelecidle3
		.pcie_hip_pipe_rxstatus0        (<connected-to-pcie_hip_pipe_rxstatus0>),        //                .rxstatus0
		.pcie_hip_pipe_rxstatus1        (<connected-to-pcie_hip_pipe_rxstatus1>),        //                .rxstatus1
		.pcie_hip_pipe_rxstatus2        (<connected-to-pcie_hip_pipe_rxstatus2>),        //                .rxstatus2
		.pcie_hip_pipe_rxstatus3        (<connected-to-pcie_hip_pipe_rxstatus3>),        //                .rxstatus3
		.pcie_hip_pipe_rxvalid0         (<connected-to-pcie_hip_pipe_rxvalid0>),         //                .rxvalid0
		.pcie_hip_pipe_rxvalid1         (<connected-to-pcie_hip_pipe_rxvalid1>),         //                .rxvalid1
		.pcie_hip_pipe_rxvalid2         (<connected-to-pcie_hip_pipe_rxvalid2>),         //                .rxvalid2
		.pcie_hip_pipe_rxvalid3         (<connected-to-pcie_hip_pipe_rxvalid3>),         //                .rxvalid3
		.pcie_hip_pipe_rxdataskip0      (<connected-to-pcie_hip_pipe_rxdataskip0>),      //                .rxdataskip0
		.pcie_hip_pipe_rxdataskip1      (<connected-to-pcie_hip_pipe_rxdataskip1>),      //                .rxdataskip1
		.pcie_hip_pipe_rxdataskip2      (<connected-to-pcie_hip_pipe_rxdataskip2>),      //                .rxdataskip2
		.pcie_hip_pipe_rxdataskip3      (<connected-to-pcie_hip_pipe_rxdataskip3>),      //                .rxdataskip3
		.pcie_hip_pipe_rxblkst0         (<connected-to-pcie_hip_pipe_rxblkst0>),         //                .rxblkst0
		.pcie_hip_pipe_rxblkst1         (<connected-to-pcie_hip_pipe_rxblkst1>),         //                .rxblkst1
		.pcie_hip_pipe_rxblkst2         (<connected-to-pcie_hip_pipe_rxblkst2>),         //                .rxblkst2
		.pcie_hip_pipe_rxblkst3         (<connected-to-pcie_hip_pipe_rxblkst3>),         //                .rxblkst3
		.pcie_hip_pipe_rxsynchd0        (<connected-to-pcie_hip_pipe_rxsynchd0>),        //                .rxsynchd0
		.pcie_hip_pipe_rxsynchd1        (<connected-to-pcie_hip_pipe_rxsynchd1>),        //                .rxsynchd1
		.pcie_hip_pipe_rxsynchd2        (<connected-to-pcie_hip_pipe_rxsynchd2>),        //                .rxsynchd2
		.pcie_hip_pipe_rxsynchd3        (<connected-to-pcie_hip_pipe_rxsynchd3>),        //                .rxsynchd3
		.pcie_hip_pipe_currentcoeff0    (<connected-to-pcie_hip_pipe_currentcoeff0>),    //                .currentcoeff0
		.pcie_hip_pipe_currentcoeff1    (<connected-to-pcie_hip_pipe_currentcoeff1>),    //                .currentcoeff1
		.pcie_hip_pipe_currentcoeff2    (<connected-to-pcie_hip_pipe_currentcoeff2>),    //                .currentcoeff2
		.pcie_hip_pipe_currentcoeff3    (<connected-to-pcie_hip_pipe_currentcoeff3>),    //                .currentcoeff3
		.pcie_hip_pipe_currentrxpreset0 (<connected-to-pcie_hip_pipe_currentrxpreset0>), //                .currentrxpreset0
		.pcie_hip_pipe_currentrxpreset1 (<connected-to-pcie_hip_pipe_currentrxpreset1>), //                .currentrxpreset1
		.pcie_hip_pipe_currentrxpreset2 (<connected-to-pcie_hip_pipe_currentrxpreset2>), //                .currentrxpreset2
		.pcie_hip_pipe_currentrxpreset3 (<connected-to-pcie_hip_pipe_currentrxpreset3>), //                .currentrxpreset3
		.pcie_hip_pipe_txsynchd0        (<connected-to-pcie_hip_pipe_txsynchd0>),        //                .txsynchd0
		.pcie_hip_pipe_txsynchd1        (<connected-to-pcie_hip_pipe_txsynchd1>),        //                .txsynchd1
		.pcie_hip_pipe_txsynchd2        (<connected-to-pcie_hip_pipe_txsynchd2>),        //                .txsynchd2
		.pcie_hip_pipe_txsynchd3        (<connected-to-pcie_hip_pipe_txsynchd3>),        //                .txsynchd3
		.pcie_hip_pipe_txblkst0         (<connected-to-pcie_hip_pipe_txblkst0>),         //                .txblkst0
		.pcie_hip_pipe_txblkst1         (<connected-to-pcie_hip_pipe_txblkst1>),         //                .txblkst1
		.pcie_hip_pipe_txblkst2         (<connected-to-pcie_hip_pipe_txblkst2>),         //                .txblkst2
		.pcie_hip_pipe_txblkst3         (<connected-to-pcie_hip_pipe_txblkst3>),         //                .txblkst3
		.pcie_hip_pipe_txdataskip0      (<connected-to-pcie_hip_pipe_txdataskip0>),      //                .txdataskip0
		.pcie_hip_pipe_txdataskip1      (<connected-to-pcie_hip_pipe_txdataskip1>),      //                .txdataskip1
		.pcie_hip_pipe_txdataskip2      (<connected-to-pcie_hip_pipe_txdataskip2>),      //                .txdataskip2
		.pcie_hip_pipe_txdataskip3      (<connected-to-pcie_hip_pipe_txdataskip3>),      //                .txdataskip3
		.pcie_hip_pipe_rate0            (<connected-to-pcie_hip_pipe_rate0>),            //                .rate0
		.pcie_hip_pipe_rate1            (<connected-to-pcie_hip_pipe_rate1>),            //                .rate1
		.pcie_hip_pipe_rate2            (<connected-to-pcie_hip_pipe_rate2>),            //                .rate2
		.pcie_hip_pipe_rate3            (<connected-to-pcie_hip_pipe_rate3>),            //                .rate3
		.pcie_hip_serial_rx_in0         (<connected-to-pcie_hip_serial_rx_in0>),         // pcie_hip_serial.rx_in0
		.pcie_hip_serial_rx_in1         (<connected-to-pcie_hip_serial_rx_in1>),         //                .rx_in1
		.pcie_hip_serial_rx_in2         (<connected-to-pcie_hip_serial_rx_in2>),         //                .rx_in2
		.pcie_hip_serial_rx_in3         (<connected-to-pcie_hip_serial_rx_in3>),         //                .rx_in3
		.pcie_hip_serial_tx_out0        (<connected-to-pcie_hip_serial_tx_out0>),        //                .tx_out0
		.pcie_hip_serial_tx_out1        (<connected-to-pcie_hip_serial_tx_out1>),        //                .tx_out1
		.pcie_hip_serial_tx_out2        (<connected-to-pcie_hip_serial_tx_out2>),        //                .tx_out2
		.pcie_hip_serial_tx_out3        (<connected-to-pcie_hip_serial_tx_out3>),        //                .tx_out3
		.pcie_npor_npor                 (<connected-to-pcie_npor_npor>),                 //       pcie_npor.npor
		.pcie_npor_pin_perst            (<connected-to-pcie_npor_pin_perst>),            //                .pin_perst
		.reset_reset_n                  (<connected-to-reset_reset_n>)                   //           reset.reset_n
	);

