/*
 * This file is auto-generated by PetaLinux SDK 
 * DO NOT MODIFY this file, the modification will not persist
 */

#ifndef __PLNX_CONFIG_H
#define __PLNX_CONFIG_H

/* The following table includes the supported baudrates */


#define CONFIG_SYS_BAUDRATE_TABLE  { 300, 600, 1200, 2400, 4800, 9600, 19200, 38400, 57600, 115200, 230400 }



/* processor - microblaze_0 */
#define XILINX_USE_MSR_INSTR	1
#define XILINX_USE_ICACHE	1
#define XILINX_USE_DCACHE	1
#define XILINX_DCACHE_BYTE_SIZE	16384
#define XILINX_PVR	2
#define MICROBLAZE_V5
#define CONFIG_CMD_IRQ
#define CONFIG_DCACHE
#define CONFIG_ICACHE

/* main_memory - ddr4_0 */

/* uart - axi_uart16550_0 */
#define CONFIG_SYS_NS16550_COM1	((XILINX_UART16550_BASEADDR & ~0xF) + 0x1000)
#define CONFIG_SYS_NS16550_REG_SIZE	-4
#define CONSOLE_ARG	"console=console=ttyS0,115200\0"
#define CONFIG_SYS_NS16550_SERIAL
#define CONFIG_CONS_INDEX	1
#define ESERIAL0	"eserial0=setenv stdout eserial0;setenv stdin eserial0\0"
#define SERIAL_MULTI  "serial=setenv stdout serial;setenv stdin serial\0"
#define CONFIG_SYS_NS16550_CLK	100000000
#define CONFIG_BAUDRATE	115200

/* spi_flash - axi_quad_spi_0 */
#define XILINX_SPI_FLASH_BASEADDR	0x44A10000
#define XILINX_SPI_FLASH_HIGHADDR	0x44A1FFFF
#define XILINX_SPI_FLASH_SCK_RATIO	2
#define XILINX_SPI_FLASH_MAX_FREQ	(XILINX_SPI_FLASH_ACLK / XILINX_SPI_FLASH_SCK_RATIO)
#define CONFIG_SYS_SPI_BASE	XILINX_SPI_FLASH_BASEADDR
#define CONFIG_ENV_SPI_MAX_HZ	XILINX_SPI_FLASH_MAX_FREQ
#define XILINX_SPI_FLASH_ACLK	100000000
#define XILINX_SPI_FLASH_CS	0

/* timer - axi_timer_0 */

/* intc - microblaze_0_axi_intc */

/* FPGA */

/* Memory testing handling */
#define CONFIG_SYS_MEMTEST_START	0x80000000
#define CONFIG_SYS_MEMTEST_END	(0x80000000 + 0x1000)
#define CONFIG_SYS_LOAD_ADDR	0x80000000 /* default load address */

/* global pointer options */

/* Size of malloc() pool */

/* stack */
#define CONFIG_SYS_INIT_SP_OFFSET	(CONFIG_SYS_TEXT_BASE - CONFIG_SYS_MALLOC_F_LEN)

/* No of_control support yet*/


/* BOOTP options */
#define CONFIG_BOOTP_SERVERIP
#define CONFIG_BOOTP_BOOTFILESIZE
#define CONFIG_BOOTP_BOOTPATH
#define CONFIG_BOOTP_GATEWAY
#define CONFIG_BOOTP_HOSTNAME
#define CONFIG_BOOTP_MAY_FAIL
#define CONFIG_BOOTP_DNS
#define CONFIG_BOOTP_SUBNETMASK
#define CONFIG_BOOTP_PXE

/*Command line configuration.*/
#define CONFIG_CMDLINE_EDITING
#define CONFIG_AUTO_COMPLETE

#define CONFIG_SUPPORT_RAW_INITRD

/* Miscellaneous configurable options */
#define CONFIG_SYS_CBSIZE	2048/* Console I/O Buffer Size      */
#define CONFIG_SYS_PBSIZE	(CONFIG_SYS_CBSIZE + sizeof(CONFIG_SYS_PROMPT) + 16)
#define CONFIG_SYS_BARGSIZE CONFIG_SYS_CBSIZE

/* Use the HUSH parser */
#define CONFIG_SYS_PROMPT_HUSH_PS2 "> "

#define CONFIG_ENV_VARS_UBOOT_CONFIG
#define CONFIG_ENV_OVERWRITE	/* Allow to overwrite the u-boot environment variables */

#define CONFIG_LMB

/* FDT support */
#define CONFIG_DISPLAY_BOARDINFO_LATE


/* architecture dependent code */
#define CONFIG_XILINX_MICROBLAZE0_USR_EXCEP    /* user exception */
#define CONFIG_SYS_HZ   1000

/* Boot Argument Buffer Size */
#define CONFIG_SYS_MAXARGS     32      /* max number of command args */
#define CONFIG_SYS_LONGHELP


/* Initial memory map for Linux */
#define CONFIG_SYS_BOOTMAPSZ 0x8000000

#endif /* __PLNX_CONFIG_H */
